# Import Data and Packages

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# Import and filter out songs from 2010 to the present
data = pd.read_csv('/Users/user/Documents/Đồ án tốt nghiệp/archive/data_o.csv')
data = data[data['year'] >= 2010]

# lowercase string columns
data['name'] = data['name'].str.lower()
data['artists'] = data['artists'].str.lower()
data

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
17606,0.434,2010,0.01510,['bruno mars'],0.637,220733,0.843,0,7BqBn9nzAq8spo5e7cZ0dJ,0.000000,5,0.0876,-5.413,1,just the way you are,81,2010-10-05,0.0432,109.012
17607,0.795,2010,0.18500,['train'],0.673,216773,0.886,0,4HlFJV71xXKIGcU3kRyttv,0.000000,1,0.0826,-4.440,0,"hey, soul sister",83,2010-12-01,0.0431,97.012
17608,0.361,2010,0.00544,"['waka flocka flame', 'roscoe dash', 'wale']",0.760,263773,0.595,1,03tqyYWC9Um2ZqU0ZN849H,0.000000,1,0.2410,-6.366,1,no hands (feat. roscoe dash & wale),76,2010-10-01,0.0391,131.497
17609,0.504,2010,0.02750,['miguel'],0.684,195373,0.603,0,0JXXNGljqupsJaZsgSbMZV,0.000311,11,0.1910,-8.127,0,sure thing,78,2010-11-26,0.0989,81.000
17610,0.065,2010,0.51200,['bruno mars'],0.523,217867,0.606,0,161DnLWsx1i3u1JT05lzqU,0.000000,1,0.1060,-4.754,0,talking to the moon,77,2010-10-05,0.0301,145.837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170648,0.608,2020,0.08460,"['anuel aa', 'daddy yankee', 'karol g', 'ozuna...",0.786,301714,0.808,0,0KkIkfsLEJbrcIhYsCL7L5,0.000289,7,0.0822,-3.702,1,china,72,2020-05-29,0.0881,105.029
170649,0.734,2020,0.20600,['ashnikko'],0.717,150654,0.753,0,0OStKKAuXlxA0fMH54Qs6E,0.000000,7,0.1010,-6.020,1,halloweenie iii: seven days,68,2020-10-23,0.0605,137.936
170650,0.637,2020,0.10100,['mamamoo'],0.634,211280,0.858,0,4BZXVFYCb76Q0Klojq4piV,0.000009,4,0.2580,-2.226,0,aya,76,2020-11-03,0.0809,91.688
170651,0.195,2020,0.00998,['eminem'],0.671,337147,0.623,1,5SiZJoLXp3WOl3J4C8IK0d,0.000008,2,0.6430,-7.161,1,darkness,70,2020-01-17,0.3080,75.055
170652,0.642,2020,0.13200,"['kevvo', 'j balvin']",0.856,189507,0.721,1,7HmnJHfs0BkFzX4x8j0hkl,0.004710,7,0.1820,-4.928,1,billetes azules (with j balvin),74,2020-10-16,0.1080,94.991

In [3]:
# Drop unnecessary columns
data = data.drop(['id','release_date'], axis=1)

In [4]:
# List out column names
data.columns.values

array(['valence', 'year', 'acousticness', 'artists', 'danceability',
       'duration_ms', 'energy', 'explicit', 'instrumentalness', 'key',
       'liveness', 'loudness', 'mode', 'name', 'popularity',
       'speechiness', 'tempo'], dtype=object)

In [17]:
# Rearrange column name position 
list_columns = ['name', 'artists', 'valence', 'year', 'acousticness', 'danceability', 'duration_ms',
       'energy', 'explicit', 'instrumentalness', 'key', 'liveness',
       'loudness', 'mode', 'popularity', 'speechiness', 'tempo']

data = data[list_columns]

# Reset index
data.reset_index(inplace=True, drop=True)
data.head()

,name,artists,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
0,just the way you are,['bruno mars'],0.434,2010,0.01510,0.637,220733,0.843,0,0.000000,5,0.0876,-5.413,1,81,0.0432,109.012
1,"hey, soul sister",['train'],0.795,2010,0.18500,0.673,216773,0.886,0,0.000000,1,0.0826,-4.440,0,83,0.0431,97.012
2,no hands (feat. roscoe dash & wale),"['waka flocka flame', 'roscoe dash', 'wale']",0.361,2010,0.00544,0.760,263773,0.595,1,0.000000,1,0.2410,-6.366,1,76,0.0391,131.497
3,sure thing,['miguel'],0.504,2010,0.02750,0.684,195373,0.603,0,0.000311,11,0.1910,-8.127,0,78,0.0989,81.000
4,talking to the moon,['bruno mars'],0.065,2010,0.51200,0.523,217867,0.606,0,0.000000,1,0.1060,-4.754,0,77,0.0301,145.837

In [18]:
# Function for change format of artists column
def change(df):
    df_genre = pd.DataFrame(columns=['artist'])
    for i in range(len(df.iloc[:,1])):
        row = df.iloc[i]['artists']
        row = row.replace("'", "")
        row = row.replace("[", "")
        row = row.replace("]", "")
        df_genre = df_genre.append({'artist': row}, ignore_index=True)
        
    return df_genre

In [19]:
# Apply function to get new artist column format
changed_string = change(data)
changed_string.head()

                                 artist
0                            bruno mars
1                                 train
2  waka flocka flame, roscoe dash, wale
3                                miguel
4                            bruno mars

In [21]:
# Add new artist format into dataset and combine with name song
data['artist'] = changed_string
data['song_artist'] = data[['name', 'artist']].agg(' - '.join, axis=1)
data.head()

,name,artists,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo,artist,song_artist
0,just the way you are,['bruno mars'],0.434,2010,0.01510,0.637,220733,0.843,0,0.000000,5,0.0876,-5.413,1,81,0.0432,109.012,bruno mars,just the way you are - bruno mars
1,"hey, soul sister",['train'],0.795,2010,0.18500,0.673,216773,0.886,0,0.000000,1,0.0826,-4.440,0,83,0.0431,97.012,train,"hey, soul sister - train"
2,no hands (feat. roscoe dash & wale),"['waka flocka flame', 'roscoe dash', 'wale']",0.361,2010,0.00544,0.760,263773,0.595,1,0.000000,1,0.2410,-6.366,1,76,0.0391,131.497,"waka flocka flame, roscoe dash, wale",no hands (feat. roscoe dash & wale) - waka flo...
3,sure thing,['miguel'],0.504,2010,0.02750,0.684,195373,0.603,0,0.000311,11,0.1910,-8.127,0,78,0.0989,81.000,miguel,sure thing - miguel
4,talking to the moon,['bruno mars'],0.065,2010,0.51200,0.523,217867,0.606,0,0.000000,1,0.1060,-4.754,0,77,0.0301,145.837,bruno mars,talking to the moon - bruno mars

In [22]:
# Drop out unnecessary columns
df = data.copy()
df.drop(['name', 'artists', 'artist'], axis=1, inplace=True)

# Rearrange positions of column
first_column = df.pop('song_artist')
df.insert(0, 'song_artist', first_column)
df.head()

,song_artist,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
0,just the way you are - bruno mars,0.434,2010,0.01510,0.637,220733,0.843,0,0.000000,5,0.0876,-5.413,1,81,0.0432,109.012
1,"hey, soul sister - train",0.795,2010,0.18500,0.673,216773,0.886,0,0.000000,1,0.0826,-4.440,0,83,0.0431,97.012
2,no hands (feat. roscoe dash & wale) - waka flo...,0.361,2010,0.00544,0.760,263773,0.595,1,0.000000,1,0.2410,-6.366,1,76,0.0391,131.497
3,sure thing - miguel,0.504,2010,0.02750,0.684,195373,0.603,0,0.000311,11,0.1910,-8.127,0,78,0.0989,81.000
4,talking to the moon - bruno mars,0.065,2010,0.51200,0.523,217867,0.606,0,0.000000,1,0.1060,-4.754,0,77,0.0301,145.837

### Standardize dataframe

In [33]:
# Create scaler variable
scaler = StandardScaler()

# Fit and transform the data
scaled = scaler.fit_transform(df.iloc[:,1:])

# Create a new dataset and combine it into the original dataset
df_scaled = pd.DataFrame(scaled, columns=df.columns[1:].to_list())
stand_df = pd.concat([df.iloc[:,0], df_scaled], axis=1)
stand_df.head()

,song_artist,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
0,just the way you are - bruno mars,-0.110165,-1.572924,-0.838244,0.179558,-0.036546,0.973658,-0.637453,-0.343772,-0.055449,-0.656092,0.436123,0.746686,1.526703,-0.550100,-0.400582
1,"hey, soul sister - train",1.388857,-1.572924,-0.256668,0.390175,-0.081071,1.169500,-0.637453,-0.343772,-1.169224,-0.688595,0.647112,-1.339251,1.660994,-0.551022,-0.796267
2,no hands (feat. roscoe dash & wale) - waka flo...,-0.413291,-1.572924,-0.871310,0.899167,0.447384,-0.155844,1.568742,-0.343772,-1.169224,0.341084,0.229470,0.746686,1.190973,-0.587931,0.340833
3,sure thing - miguel,0.180504,-1.572924,-0.795798,0.454530,-0.321686,-0.119409,-0.637453,-0.342449,1.615215,0.016059,-0.152392,-1.339251,1.325265,-0.036148,-1.324243
4,talking to the moon - bruno mars,-1.642405,-1.572924,0.862668,-0.487397,-0.068770,-0.105746,-0.637453,-0.343772,-1.169224,-0.536483,0.579023,-1.339251,1.258119,-0.670975,0.813677

In [34]:
# Save completed dataset into a csv file
stand_df.to_csv('preprocessed_df.csv', index=False)